// Mock client data
export const mockClients = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    phone: '(555) 123-4567',
    caseType: 'Divorce Proceedings',
    status: 'active',
    priority: 'high' as const,
    lastActivity: '2 hours ago',
    billableHours: 12.5,
  },
  {
    id: '2',
    name: 'Michael Chen',
    email: 'mchen@example.com',
    phone: '(555) 987-6543',
    caseType: 'Child Custody',
    status: 'active',
    priority: 'medium' as const,
    lastActivity: '1 day ago',
    billableHours: 8.75,
  },
  {
    id: '3',
    name: 'Jennifer Williams',
    email: 'jwilliams@example.com',
    phone: '(555) 222-3333',
    caseType: 'Child Support Modification',
    status: 'active',
    priority: 'low' as const,
    lastActivity: '3 days ago',
    billableHours: 4.25,
  },
  {
    id: '4',
    name: 'Robert Smith',
    email: 'rsmith@example.com',
    phone: '(555) 444-5555',
    caseType: 'Adoption',
    status: 'active',
    priority: 'high' as const,
    lastActivity: '5 hours ago',
    billableHours: 15.0,
  },
  {
    id: '5',
    name: 'Lisa Garcia',
    email: 'lgarcia@example.com',
    phone: '(555) 666-7777',
    caseType: 'Divorce Proceedings',
    status: 'closed',
    priority: 'medium' as const,
    lastActivity: '2 weeks ago',
    billableHours: 22.5,
  },
  {
    id: '6',
    name: 'David Wilson',
    email: 'dwilson@example.com',
    phone: '(555) 888-9999',
    caseType: 'Child Custody',
    status: 'closed',
    priority: 'low' as const,
    lastActivity: '1 month ago',
    billableHours: 16.25,
  },
];


// Mock time tracking data
export const mockTimeEntries = [
  {
    id: '1',
    client: 'Sarah Johnson',
    description: 'Case review and document preparation',
    date: '2023-08-04',
    hours: 2.5,
    billable: true,
    rate: 250,
  },
  {
    id: '2',
    client: 'Michael Chen',
    description: 'Client consultation',
    date: '2023-08-04',
    hours: 1.0,
    billable: true,
    rate: 250,
  },
  {
    id: '3',
    client: 'Jennifer Williams',
    description: 'Court appearance',
    date: '2023-08-03',
    hours: 3.5,
    billable: true,
    rate: 300,
  },
  {
    id: '4',
    client: 'Robert Smith',
    description: 'Phone call with opposing counsel',
    date: '2023-08-03',
    hours: 0.75,
    billable: true,
    rate: 250,
  },
  {
    id: '5',
    client: 'Sarah Johnson',
    description: 'Research for motion',
    date: '2023-08-02',
    hours: 2.0,
    billable: true,
    rate: 250,
  },
];

// Mock invoice data
export const mockInvoices = [
  {
    id: 'INV-2023-001',
    client: 'Sarah Johnson',
    amount: 3125.00,
    date: '2023-08-01',
    dueDate: '2023-08-15',
    status: 'unpaid',
    hours: 12.5,
  },
  {
    id: 'INV-2023-002',
    client: 'Michael Chen',
    amount: 2187.50,
    date: '2023-07-25',
    dueDate: '2023-08-08',
    status: 'unpaid',
    hours: 8.75,
  },
  {
    id: 'INV-2023-003',
    client: 'Lisa Garcia',
    amount: 5625.00,
    date: '2023-07-15',
    dueDate: '2023-07-29',
    status: 'paid',
    hours: 22.5,
  },
  {
    id: 'INV-2023-004',
    client: 'Robert Smith',
    amount: 3750.00,
    date: '2023-07-10',
    dueDate: '2023-07-24',
    status: 'paid',
    hours: 15.0,
  },
  {
    id: 'INV-2023-005',
    client: 'David Wilson',
    amount: 4062.50,
    date: '2023-07-01',
    dueDate: '2023-07-15',
    status: 'paid',
    hours: 16.25,
  },
];